DELETE http://localhost:9001/accounts/097fbe08-e8cb-4a40-ac47-4099e95bd505/watchlist

###
POST http://localhost:9001/accounts/097fbe08-e8cb-4a40-ac47-4099e95bd505/watchlist
Content-Type: application/json

{
  "assets": [
    {
      "symbol": "AMZN"
    },
    {
      "symbol": "GOOG"
    },
    {
      "symbol": "TSLA"
    }
  ]
}

