version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 5
    environment:
      # Create db
      POSTGRES_DB: vertx-stock-broker
      # Use postgres/secret user/password credentials
      POSTGRES_PASSWORD: secret
      # enforce UTC timezone
      TZ: UTC
    volumes:
      - vertx-stock-broker-data-local:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4
    ports:
      - 8081:8080

# permanent storage of data.
# > docker volume rm postgres_vertx-stock-broker-data-local
volumes:
  vertx-stock-broker-data-local:
